export const audioFiles: string[] = [
    'stratagem-input-beep-1',
    'stratagem-input-beep-2',
    'stratagem-input-beep-3',
    'stratagem-input-beep-4',
    'stratagem-input-beep-5',
    'stratagem-input-beep-6',
    'stratagem-input-beep-7',
    'stratagem-input-beep-8',
    'stratagem-input-fail-1',
    'stratagem-input-fail-2',
    'stratagem-input-ready-long',
    'stratagem-input-deploy',
    'stratagem-deploy-droppod',
    'stratagem-deploy-pelican',
]